### ISSUE TITLE
[Bug] The exception message is not suitable.

### ISSUE THREAD

**Issue by BigSlick11** [jundoll/discordbot-BSPlaylistManager#29]
The exception message following is not suitable when input a non supported URL:

```
Traceback (most recent call last):
  File "discordbot.py", line 97, in getSongInfo
    raise Exception
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.7/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "discordbot.py", line 134, in add
    songInfo = getSongInfo(arg)
  File "discordbot.py", line 99, in getSongInfo
    raise Exception
Exception
```
The message should be "bsaber.comで頼む"

**Comment by jundoll** [comment]
こちらに合わせて対処しました。https://github.com/jundoll/discordbot-BSPlaylistManager/issues/28
